### ISSUE TITLE
CMake 构建失败

### ISSUE THREAD

**Issue by MakingL** [chenBright/tinyWS#76]
您好，我比较关心 多线程实现的代码，我 clone 了代码，并 Cmake 构建，但是没能构建成功，貌似是 AsyncLogger.cpp 文件没有编译通过，我看了一下  muduo 中的代码，貌似这个文件是您新添加的，我的报错信息如下：

![failed](https://user-images.githubusercontent.com/31580426/76943481-644cdd00-693a-11ea-95fb-c8bf2b829e61.png)

我的环境如下: 
![env](https://user-images.githubusercontent.com/31580426/76943913-15537780-693b-11ea-99e6-b4d889b57710.png)

**Comment by chenBright** [comment]
不好意思，最近比较忙，没有即使回复。

你是回滚到某个版本了吗？因为之前的确是有AsyncLogger导致编译错误的问题。

我clone了代码，编译时没问题的。

我用的命令如下：
```shell
mkdir build
cd build
cmake ../
make tinyWS_thread
```

我的 make 版本和你的一样。
