### ISSUE TITLE
多线程

### ISSUE THREAD

**Issue by StevenHD** [chenBright/tinyWS#80]
多线程文件夹中的base和net的区别是什么啊？

**Comment by chenBright** [comment]
base是一些通用的组件，例如锁、线程池等，net下只是网络库的组件。

**Comment by ghost** [comment]
你好，收到http请求后，我想用线程池来执行耗时操作可行么？我看muduo里有ThreadPool，这个应该怎么结合一下呢？求解

**Comment by chenBright** [comment]
> 你好，收到http请求后，我想用线程池来执行耗时操作可行么？我看muduo里有ThreadPool，这个应该怎么结合一下呢？求解
只要将耗时的操作封装成一个线程池的Task，将其放到线程池里就行了。涉及到网络库的对象的api，基本都提供了线程安全的保证，可以安全地在线程池里被调用的。
